<?php
/**
 * Created by PhpStorm.
 * User: mohamed
 * Date: 3/31/2018
 * Time: 7:45 PM
 */

namespace App\Http\Controllers;


use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class PagesController extends Controller
{

    public function getAbout()
    {
        $fname="mohammed";
        $lname="elamin";
        $fullname=$fname." :".$lname;
        $email="mohammedelamin14.me@gmail.com";
        return view('pages.about')->withFullname($fullname)->withEmail($email); // TODO: Change the autogenerated stub
    }


    public function getWelcome()
    {

        $posts=Post::orderBy('id','desc')->limit(4)->get();

        return view('pages.welcome')->withPosts($posts); // TODO: Change the autogenerated stub
    }



    public function getContact()
    {
        return view('pages.contact'); // TODO: Change the autogenerated stub
    }

    public  function postContact(Request $request){

        $this->validate($request,[
            'email'=>'required | email '
            ,'subject'=>'required | min:5 | max:30'
            ,'body_message'=>'required | min:10 | max:255'
        ]);

$data=array
(
'email'=>$request->email,
'subject'=>$request->subject,
'body_message'=>$request->body_message

);
     Mail::send('emails.contact',$data,function ($message) use ($data){
         $message->from($data['email']);
         $message->to('mohamedelamin14.me@gmail.com');
         $message->subject($data['subject']);




     });

     Session::flash('success','your mail has been send');



     return redirect('/');

    }

}